SMODS.Joker {
    key = "art",
    unlocked = false,
    unlock_condition = { type = "", extra = "", hidden = true },
    locked_loc_vars = function(self, info_queue, card)
        -- Force Steamodded's locked-Joker path to initialise specific_vars and
        -- use the same hidden Legendary message as vanilla Soul Jokers.
        return { key = "joker_locked_legendary", set = "Other", vars = {} }
    end,
    discovered = false,
    rarity = 4,
    cost = 20,
    atlas = "Jokers",
    pos = { x = 6, y = 2 },
    soul_pos = { x = 1, y = 3 },
    config = { extra = { tags = 1 } },
    loc_vars = function (self, info_queue, card)
        return { vars = { card.ability.extra.tags } }
    end,
    calculate = function (self, card, context)
        if context.selling_self then
            for _ = 1, card.ability.extra.tags do
                G.E_MANAGER:add_event(Event({
                    func = function ()
                        add_tag(HNDS.poll_tag("_hnds_art"))
                        play_sound('holo1', 1.2 + math.random() * 0.1, 0.4)
                        return true
                    end
                }))
            end
            G.GAME.art_queue = (G.GAME.art_queue or 0) + card.ability.extra.tags
            return nil, true
        end
    end,
    attributes = { "generation", "on_sell", "tag" }
}
-- Art the Clown: add one native booster slot before the pack is built.
-- The pending state lives on the exact booster card, avoiding global/index
-- mismatches, and the queue is consumed only when Art is actually created.
if Card and Card.open and not Card._hnds_art_open_wrapped then
    Card._hnds_art_open_wrapped = true
    local hnds_card_open = Card.open
    function Card:open(...)
        local queued_art = G and G.GAME
            and (tonumber(G.GAME.art_queue) or 0) > 0
            and self.ability
            and self.ability.set == 'Booster'
            and not self.hnds_art_pending
        local original_size = queued_art and tonumber(self.ability.extra) or nil

        if not original_size then
            return hnds_card_open(self, ...)
        end

        local size_mod = tonumber(G.GAME.modifiers and G.GAME.modifiers.booster_size_mod) or 0
        self.hnds_art_pending = true
        self.hnds_art_target_index = math.max(1, original_size + size_mod + 1)

        -- Steamodded derives both the pack CardArea capacity and its centred width
        -- from this value, exactly as it does for the Stuffed voucher modifier.
        -- Booster cards are generated by a delayed event after Card:open returns,
        -- so this must remain increased until the consumed booster finishes opening.
        self.ability.extra = original_size + 1
        return hnds_card_open(self, ...)
    end
end

-- Pack-generation contexts fire outside any single card's calculate, so the
-- Art injection and cleanup ride the mod-level context registry.
HNDS.on_context(function(context)
    -- Make the added final slot Art itself. Because this runs inside
    -- Steamodded's normal booster creation loop, Art is centred and spaced
    -- together with every other option, including packs enlarged by Stuffed
    -- or other booster-size modifiers.
    if context.create_booster_card and context.booster
        and context.booster.hnds_art_pending
        and context.index == context.booster.hnds_art_target_index
    then
        context.booster.hnds_art_pending = nil
        context.booster.hnds_art_target_index = nil
        G.GAME.art_queue = math.max(0, (tonumber(G.GAME.art_queue) or 1) - 1)
        return {
            booster_create_flags = {
                key = "j_hnds_art",
                area = G.pack_cards,
                no_edition = true,
                stickers = {},
            }
        }
    end

    -- Belt-and-suspenders cleanup for the forced Art option: other generation
    -- hooks cannot leave it with an Edition or a Sticker.
    if context.modify_booster_card and context.card
        and context.card.config and context.card.config.center
        and context.card.config.center.key == "j_hnds_art"
    then
        context.card:set_edition(nil, true, true)
        for sticker_key, _ in pairs(SMODS.Stickers or {}) do
            context.card.ability[sticker_key] = nil
        end
    end
end)
