[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.FUNCS.toggle_shop = function(e)"
position = "after"
payload = '''
    if HNDS and HNDS.handle_blood_cursed_shop_exit then
        HNDS.handle_blood_cursed_shop_exit()
    end
'''
match_indent = true
times = 1
