[manifest]
version = "1.0.0"
dump_lua = true
priority = 20


[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
local rows = 6
    local cols = 5
'''
position = "at"
payload = '''
local rows = 7
    local cols = 5
'''
match_indent = false
times = 1

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
local cols = 5
    local rows = 6
'''
position = "at"
payload = '''
local cols = 5
    local rows = 7
'''
match_indent = false
times = 1


[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/ui.lua"]'
pattern = '''return SMODS.card_collection_UIBox(SMODS.Stickers, { 5, 5 }, {'''
position = "at"
payload = '''return SMODS.card_collection_UIBox(SMODS.Stickers, { 4, 4 }, {'''
match_indent = true
times = 1
