[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Platinum Stake: Track the chips scored in the very last hand of the round
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.chips = G.GAME.chips + hand_chips"
position = "after"
payload = "G.GAME.hnds_last_hand_chips = hand_chips"
match_indent = true
times = 1
