[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.regex]
target = "game.lua"
pattern = '''(?m)^(?<indent>[\t ]*)if (?<cond>[^\n]*(?:G|self)\.GAME\.chips[^\n]*(?:G|self)\.GAME\.blind\.chips[^\n]*G\.GAME\.current_round\.hands_left[^\n]*) then'''
position = "at"
line_prepend = "$indent"
payload = '''
if ($cond) and not (HNDS and HNDS.public_nuisance_should_continue and HNDS.public_nuisance_should_continue()) then
'''
times = 1
