[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# -----------------------------
# Standard Packs: Force drawing a hand if spectrum is in a pack
# -----------------------------

# Force draw_hand when Spectrum appears in Standard Packs
# very possible to make it selectable into consumables but probably not a great idea for a rare consumable
# This workaround forces draw_from_deck_to_hand() to make it selectable and alert the player
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
                    for k, v in ipairs(pack_cards) do
                        G.pack_cards:emplace(v)
                    end
'''
position = "after"
match_indent = true
payload = '''
                    -- Force draw_hand when Spectrum appears so it's useable
                    if self.ability.name and self.ability.name:find('Standard') and G.FUNCS and G.FUNCS.draw_from_deck_to_hand then
                        local has_spectrum = false
                        for _, c in ipairs(pack_cards) do
                            if c and c.config and c.config.center_key and c.config.center_key == "c_hnds_spectrum" then
                                has_spectrum = true
                                break
                            end
                        end
                        if has_spectrum then
                            G.FUNCS.draw_from_deck_to_hand()
                        end
                    end
'''
