[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# -----------------------------
# Standard Packs: Force drawing a hand if spectrum is in a pack
# -----------------------------

# Force draw_hand when Spectrum appears in Standard Packs
# very possible to make it selectable into consumables but probably not a great idea for a rare consumable
# This workaround forces draw_from_deck_to_hand() to make it selectable and alert the player
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
if self.draw_hand == true then G.FUNCS.draw_from_deck_to_hand() end
'''
position = "after"
match_indent = true
payload = '''
if self.draw_hand ~= true and self.kind == "Standard" then
    for _, c in ipairs(G.pack_cards.cards) do
        if c.config and c.config.center_key == "c_hnds_spectrum" then
            G.FUNCS.draw_from_deck_to_hand()
            break
        end
    end
end
'''
