SMODS.Challenge {
	key = 'gambling_opportunity',
	loc_txt = {
		name = 'Gambling Opportunity',
	},
	rules = {
		custom = {
			{ id = 'hnds_gambling_opportunity' },
			{ id = 'no_interest' },
			{ id = 'no_extra_hand_money' },
			{ id = 'no_reward' },
		},
		modifiers = {
			{ id = 'dollars', value = 0 },
		},
	},
	jokers = {
		{ id = 'j_hnds_jackpot', eternal = true, edition = 'negative' },
	},
	consumeables = { },
	vouchers = {
		{ id = 'v_hone', type = 'voucher' },
	},
	deck = {
		type = 'Challenge Deck',
		cards = {
			{ s = 'S', r = 'A' }, { s = 'S', r = 'K' }, { s = 'S', r = 'Q' }, { s = 'S', r = 'J' }, { s = 'S', r = 'T' }, { s = 'S', r = '9' }, { s = 'S', r = '8' }, { s = 'S', r = '7' }, { s = 'S', r = '7', }, { s = 'S', r = '6' }, { s = 'S', r = '5' }, { s = 'S', r = '4' }, { s = 'S', r = '3' },
			{ s = 'H', r = 'A' }, { s = 'H', r = 'K' }, { s = 'H', r = 'Q' }, { s = 'H', r = 'J' }, { s = 'H', r = 'T' }, { s = 'H', r = '9' }, { s = 'H', r = '8' }, { s = 'H', r = '7', }, { s = 'H', r = '7', }, { s = 'H', r = '6' }, { s = 'H', r = '5' }, { s = 'H', r = '4' }, { s = 'H', r = '3' },
			{ s = 'C', r = 'A' }, { s = 'C', r = 'K' }, { s = 'C', r = 'Q' }, { s = 'C', r = 'J' }, { s = 'C', r = 'T' }, { s = 'C', r = '9' }, { s = 'C', r = '8' }, { s = 'C', r = '7', }, { s = 'C', r = '7', }, { s = 'C', r = '6' }, { s = 'C', r = '5' }, { s = 'C', r = '4' }, { s = 'C', r = '3' },
			{ s = 'D', r = 'A' }, { s = 'D', r = 'K' }, { s = 'D', r = 'Q' }, { s = 'D', r = 'J' }, { s = 'D', r = 'T' }, { s = 'D', r = '9' }, { s = 'D', r = '8' }, { s = 'D', r = '7', }, { s = 'D', r = '7', }, { s = 'D', r = '6' }, { s = 'D', r = '5' }, { s = 'D', r = '4' }, { s = 'D', r = '3' },
		},
	},
	restrictions = {
		banned_cards = {
			{ id = 'j_bootstraps' },
			{ id = 'j_bull' },
			{ id = 'j_credit_card' },
			{ id = 'j_delayed_grat' },
			{ id = 'j_business' },
			{ id = 'j_egg' },
			{ id = 'j_faceless' },
			{ id = 'j_todo_list' },
			{ id = 'j_cloud_9' },
			{ id = 'j_midas_mask' },
			{ id = 'j_gift' },
			{ id = 'j_reserved_parking' },
			{ id = 'j_mail' },
			{ id = 'j_to_the_moon' },
			{ id = 'j_golden' },
			{ id = 'j_trading' },
			{ id = 'j_ticket' },
			{ id = 'j_rough_gem' },
			{ id = 'j_rocket' },
			{ id = 'j_satellite' },
			{ id = 'j_hnds_coffee_break' },
			{ id = 'j_hnds_ms_fortune' },
			{ id = 'c_hermit' },
			{ id = 'c_devil' },
			{ id = 'c_magician' },
			{ id = 'c_talisman' },
			{ id = 'c_temperance' },
			{ id = 'c_immolate' },
			{ id = 'v_clearance_sale' },
			{ id = 'v_liquidation' },
			{ id = 'v_seed_money' },
			{ id = 'v_money_tree' },
			{ id = 'e_hnds_vintage' },
		},
		banned_tags = {
			{ id = 'tag_investment' },
			{ id = 'tag_economy' },
			{ id = 'tag_skip' },
			{ id = 'tag_hnds_mystery_tag' },
		},
		banned_other = {
			{ id = 'bl_ox', type = 'blind' },
			{ id = 'bl_tooth', type = 'blind' },
		},
	},
}
